os: osx
osx_image: xcode9.2
language: swift
xcode_workspace: Browsy.xcworkspace
xcode_scheme: Browsy
script:
  - xcodebuild -workspace Browsy.xcworkspace -scheme Browsy -configuration Release build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
